import {  useContext, useState } from "react"
import "./loginPop.css"
import { StoreContext } from "../context/StoreContext";
import axios from "axios"

function LoginPop({setShowLogin}) {

  const {url, token, setToken} = useContext(StoreContext);

  const [currState, setCurrState] = useState("Sign Up");

  const [data, setData] = useState({
    name:"",
    email:"",
    password:""
  });

  const onChangeHandler = (event) => {
    const name = event.target.name;
    const value = event.target.value;
    setData(data => ({...data, [name]: value}))
  }

  const onLogin = async (event) => {
    event.preventDefault();
    let newUrl = url;
    if(currState==="Login"){
      newUrl += "api/user/login";
    }
    else {  // if state is not login then it is signin
      newUrl += "api/user/register";
    }

    const response = await axios.post(newUrl, data);

    if(response.data.success){  // it means we have registered, and we get a  token which is stored in StoreContext
      // it means we have registered, and we get a token which is stored in StoreContext
      setToken(response.data.token);
      localStorage.setItem("token", response.data.token) // - Saves the token in the browser’s localStorage. - This ensures the token persists even if the user refreshes the page or closes/reopens the browser.
      setShowLogin(false); // after performing above function, we will do setShowLogin(false) to hide login page
    } 
    else {
      alert(response.data.message);
    }

  }

  return (
    <div className="login-popup">
      <form onSubmit={onLogin} className="login-popup-container" >
        <div className="login-popup-title">
          <h2>{currState}</h2>
          <p onClick={() => setShowLogin(false)} ><span className=" cross-icon material-symbols-outlined">close_small</span></p>
        </div>
        <div className="login-popup-inputs">
          {
            currState==="Login" ?
            <></> :
            <input name="name" onChange={onChangeHandler} value={data.name} type="text" placeholder="Your name" required />
          }
          <input name="email" onChange={onChangeHandler} value={data.email} type="email" placeholder="Your email" required  />
          <input name="password" onChange={onChangeHandler} value={data.password} type="password" placeholder="Your password" required />
        </div>
        <button type="submit" className="sign-login">{currState==="Sign Up" ? "Create account": "Login"}</button>
        <div className="login-popup-condition">
          <input type="checkbox" required />
          <p>By continuing, i agree to the terms of use & privacy policy. </p>
        </div>
        {
          currState==="Login"? <p>Create a new account? <span className="color-login-sign" onClick={() => setCurrState("Sign Up")}>Click here</span> </p>
          : <p>Already have an account? <span className="color-login-sign" onClick={() => setCurrState("Login")}>Login here</span> </p>
        }
        
      </form>
    </div>
  )
}

export default LoginPop

/**
    const name = event.target.name; refers to the input element that triggered the change.
    .name is  the attribute of that input [<input name="email />"]
    .value is the current text/value inside that input field
    setData(data => ({...data, [name]: value}))
    Takes the previous state,
    spreads it (...data) so all existing fields remain unchanged
    - Updates only the field with the matching [name] to [value]
    TOKEN -
    - A token is a unique string (often a JWT – JSON Web Token) generated by the server after a user successfully logs in or registers.
    - It acts like a digital key or ID card that proves the user’s identity.


 */